@startuml

!include ../global/stylesheet.iuml
hide empty description

[*] --> NEW
NEW --> RUNNABLE : start
RUNNABLE -up-> BLOCKED : synchronized争取锁
BLOCKED --> RUNNABLE : synchronized获取到锁
RUNNABLE -right-> WAITING
note on link
  * Object.wait()
  * Thread.join()
  * LockSupport.park()
end note
WAITING --> RUNNABLE
note on link
  * Object.notify()
  * Object.notifyAll()
  * LockSupport.unpark(Thread)
end note
RUNNABLE --> TERMINATED : run方法运行结束
RUNNABLE --> TIMED_WAITING
note on link
  * Object.wait(long)
  * Thread.join(long)
  * Thread.sleep(long)
  * LockSupport.park(long)
end note
TIMED_WAITING --> RUNNABLE
note on link
  * Object.notify()
  * Object.notifyAll()
  * LockSupport.unpark(Thread)
end note
TERMINATED --> [*]

@enduml
