apiVersion: v1
kind: Service
metadata:
    name: springboot-demo
    namespace: springboot
spec:
    type: NodePort
    selector:
        app: springboot-demo
    ports:
    - port: 8081 #内网端口
      targetPort: 8080 #容器端口
      nodePort: 30008 #外网端口
