apiVersion: v1
kind: Pod
metadata:
    name: springboot-demo
    namespace: springboot
spec:
    containers:
    - name: springboot-demo
      image: registry.cn-qingdao.aliyuncs.com/jy-test/boot:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
        hostPort: 8080
      livenessProbe:
          httpGet:
              port: 8080
              path: /probe
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 1
          timeoutSeconds: 5
