apiVersion: v1
kind: ReplicationController
metadata:
    name: springboot-demo
    namespace: springboot
spec:
    replicas: 2
    selector:
        app: springboot-demo
    template:
        metadata:
            name: springboot-demo
            labels:
                app: springboot-demo
        spec:
            containers:
            - name: springboot-demo
              image: registry.cn-qingdao.aliyuncs.com/jy-test/boot
              imagePullPolicy: Always
              ports:
              - containerPort: 8080
                hostPort: 8080
