apiVersion: v1
kind: Service
metadata:
    name: springboot-demo
spec:
    type: NodePort
    sessionAffinity: RoundRobin
    selector:
        app: springboot-demo
    ports:
    - port: 8081
      targetPort: 8080
      nodePort: 30081
