apiVersion: v1
kind: ReplicationController
metadata:
    name: springboot-demo
    labels:
        app: springboot-demo
spec:
    replicas: 2
    template:
        metadata:
            name: springboot-demo
            labels:
                app: springboot-demo
        spec:
            containers:
            - name: springboot-demo
              image: registry.cn-qingdao.aliyuncs.com/jy-test/boot
              ports:
              - containerPort: 8080
