apiVersion: v1
kind: Pod
metadata:
    name: kubia
spec:
    imagePullSecrets:
        - name: aliyuncs
    containers:
        - name: kubia
          image: registry.cn-hangzhou.aliyuncs.com/kubia
          imagePullPolicy: IfNotPresent
          ports:
              - containerPort: 8000
                protocol: TCP
