spring:
  datasource:
    username: jy
    password: 123456
    url: jdbc:postgresql:mybatis-demo
mybatis-plus:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  mapper-locations: classpath*:/mappers/*.xml
