spring:
  datasource:
    url: jdbc:postgresql://workstation.local:5432/mybatis-demo
    username: jy
    password: 123456
mybatis-plus:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  mapper-locations: classpath*:/mappers/*.xml
