spring:
  application:
    name: web-demo
arthas:
  tunnel-server: ws://127.0.0.1:7777/ws
  agent-id: ${spring.application.name}-${random.value}
  telnet-port: -1
  http-port: -1

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - arthas
