@startmindmap

!theme sandstone

* Database Cluster
** Database
*** Schema
**** Table
**** Index
***** B-tree
***** Hash
***** GIN
***** GiST
***** SP-GiST
***** BRIN
**** View
**** Transaction
**** Function
**** Sequence
*** Extension
** Database 2 ...
** Global Objects

@endmindmap