spring:
  application:
    name: session-demo
  session:
    store-type: redis
    redis:
      repository-type: indexed
      configure-action: none
      cleanup-cron: 0 0/30 * * * ?
  data:
    redis:
      host: 192.168.0.113
      password: admin
logging:
  level:
    org.springframework.session: debug
    org.springframework.test: debug
