spring:
  application:
    name: session-demo
  session:
    store-type: redis
    redis:
      cleanup-cron: 0 0/30 * * * ?
logging:
  level:
    org.springframework.session: debug
    org.springframework.test: debug
