spring:
  rabbitmq:
    username: rabbit
    password: 123456
    virtual-host: dev
  cloud:
    stream:
      bindings:
        demoConsumerA-in-0:
          destination: demo.topic
          group: groupA
        demoConsumerB-in-0:
          destination: demo.topic
          group: groupB
      function:
        definition: demoConsumerA;demoConsumerB
