spring:
  rabbitmq:
    username: rabbit
    password: 123456
    virtual-host: dev
  cloud:
    stream:
      default:
        consumer:
          concurrency: 4
          maxAttempts: 1
      rabbit:
        default:
          consumer:
            prefetch: 10
            autoBindDlq: true
      bindings:
        demoConsumerA-in-0:
          destination: demo.topic
          group: groupA
        demoConsumerB-in-0:
          destination: demo.topic
          group: groupB
      function:
        definition: demoConsumerA;demoConsumerB
